# Generated by Django 6.0.1 on 2026-02-07 12:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('json_data', models.JSONField()),
                ('thumbnail_url', models.URLField(blank=True, null=True)),
                ('is_gallery', models.BooleanField(db_index=True, default=False)),
                ('category', models.CharField(blank=True, choices=[('welcome', 'Welcome'), ('newsletter', 'Newsletter'), ('promotional', 'Promotional'), ('transactional', 'Transactional'), ('event', 'Event')], max_length=50)),
                ('is_draft', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='core.organization')),
            ],
            options={
                'db_table': 'templates',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['org', 'created_at'], name='templates_org_id_32d270_idx'), models.Index(fields=['is_gallery', 'category'], name='templates_is_gall_d4ba3e_idx')],
            },
        ),
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('s3_key', models.CharField(max_length=500, unique=True)),
                ('url', models.URLField()),
                ('file_size', models.IntegerField()),
                ('content_type', models.CharField(max_length=50)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('is_orphaned', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.organization')),
            ],
            options={
                'db_table': 'uploaded_images',
                'indexes': [models.Index(fields=['org', 'created_at'], name='uploaded_im_org_id_418ff9_idx'), models.Index(fields=['is_orphaned', 'created_at'], name='uploaded_im_is_orph_defffd_idx')],
            },
        ),
    ]
