# Generated by Django 5.2.1 on 2026-03-28 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_plan_stripe_price_id_plan_stripe_product_id_and_more'),
        ('templates_api', '0005_template_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='template',
            name='is_modified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='template',
            name='source_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copies', to='templates_api.template'),
        ),
        migrations.AddIndex(
            model_name='template',
            index=models.Index(fields=['org', 'source_template'], name='tmpl_org_source_idx'),
        ),
        migrations.AddConstraint(
            model_name='template',
            constraint=models.UniqueConstraint(condition=models.Q(('source_template__isnull', False)), fields=('org', 'source_template'), name='unique_org_source_template'),
        ),
    ]
