# Generated by Django 5.2.1 on 2026-03-25 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('monthly_price_usd', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('rendered_emails_limit', models.BigIntegerField(default=1000)),
                ('storage_limit_bytes', models.BigIntegerField(default=1073741824)),
                ('max_upload_size_bytes', models.BigIntegerField(default=5242880)),
                ('max_media_files_per_upload', models.PositiveIntegerField(default=5)),
                ('is_default', models.BooleanField(default=False, help_text='New orgs get this plan when no plan is specified.')),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'plans',
                'ordering': ['sort_order', 'monthly_price_usd'],
            },
        ),
        migrations.AlterField(
            model_name='organization',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations', to='core.plan'),
        ),
    ]
