# Generated by Django 5.2.1 on 2026-03-28 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_plan_stripe_price_id_plan_stripe_product_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='custom_palette',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='organization',
            name='default_palette',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
