# Generated by Django 5.2.1 on 2026-03-30 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_plan_and_account_use_mb'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='pending_plan',
            field=models.ForeignKey(blank=True, help_text='Plan to activate after current subscription period ends (downgrade).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_accounts', to='core.plan'),
        ),
    ]
