# Generated by Django 5.2.1 on 2026-03-30 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_account_pending_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='usage_limit_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='usage_warning_sent',
            field=models.BooleanField(default=False),
        ),
    ]
