# Generated by Django 5.2.1 on 2026-03-30 18:45

from django.db import migrations, models


def set_free_plan_limits(apps, schema_editor):
    Plan = apps.get_model('core', 'Plan')
    Plan.objects.filter(slug='free').update(max_organizations=1, max_api_keys_per_org=1)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_account_usage_email_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='max_api_keys_per_org',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='plan',
            name='max_organizations',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.RunPython(set_free_plan_limits, migrations.RunPython.noop),
    ]
